### ISSUE TITLE
Latest master causes build error due to not finding `AWS_ASSERT`

### ISSUE THREAD

**Issue by tdenniston** [awslabs/aws-c-event-stream#19]
When trying to build the AWS C++ SDK, it uses the `master` branch of this repo (because of https://github.com/aws/aws-sdk-cpp/issues/1145). I am seeing this build error:

```
Cloning into 'AwsCEventStream'...
Already on 'master'
CMake Warning:
  Manually-specified variables were not used by the project:

    STATIC_CRT


/Users/tyler/tiledb/TileDB/build/externals/src/ep_awssdk-build/.deps/build/src/AwsCEventStream/source/event_stream.c:315:5: error: implicit declaration of function 'AWS_ASSERT' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    AWS_ASSERT(buffer);
    ^
/Users/tyler/tiledb/TileDB/build/externals/src/ep_awssdk-build/.deps/build/src/AwsCEventStream/source/event_stream.c:315:5: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
/Users/tyler/tiledb/TileDB/build/externals/src/ep_awssdk-build/.deps/build/src/AwsCEventStream/source/event_stream.c:546:5: error: implicit declaration of function 'AWS_ASSERT' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    AWS_ASSERT(headers);
```

Some system information: macOS 10.13.6, compiler:
```
$ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Let me know if you need more information.

**Comment by justinboswell** [comment]
Looking into it, looks like a missing header.

**Comment by justinboswell** [comment]
What version of aws-c-common are you using? It looks like you are not transitively getting aws/common/assert.inl, which is included in aws/common/common.h, which you should get via aws/common/encoding.h in event_stream.c.

**Comment by tdenniston** [comment]
Since I am just using the AWS C++ SDK's build system to pull this in, it looks like they have pinned commit ac02e17 of aws-c-common:

https://github.com/aws/aws-sdk-cpp/blob/master/third-party/CMakeLists.txt#L18

**Comment by justinboswell** [comment]
I would highly recommend pinning releases instead of commits, and the release you will need is v0.3.9, you can just replace the commit hash with "v0.3.9"

**Comment by tdenniston** [comment]
It's fine with me if you want to close this issue here (since it appears to be more of a versioning issue than a build error). For my purposes I can wait for the upstream issue https://github.com/aws/aws-sdk-cpp/issues/1145 to be fixed.

**Comment by singku** [comment]
This is on us. We have fixed that. 

Some times we have bug fixes submitted in these dependencies repo like this repo, but that only means updated commits and doesn't necessarily mean tagged release. To unblock us from waiting a tagged release. We have to use commit.
