### ISSUE TITLE
Project is not buildable: AwsCFlags & Co not found

### ISSUE THREAD

**Issue by dmitryash** [awslabs/aws-c-event-stream#21]
Hello,

a project is not buildable due to error:

```
CMake Error at CMakeLists.txt:24 (include):
  include could not find load file:

    AwsCFlags


CMake Error at CMakeLists.txt:25 (include):
  include could not find load file:

    AwsSharedLibSetup


CMake Error at CMakeLists.txt:26 (include):
  include could not find load file:

    AwsSanitizers


CMake Error at CMakeLists.txt:62 (aws_set_common_properties):
  Unknown CMake command "aws_set_common_properties".
```

This is due to use `include()` cmake command which is designed to load cmake file or systemwide provided by cmake project as far as I know.

**Comment by dmitryash** [comment]
The project should provide all there files

**Comment by bretambrose** [comment]
This project depends on both aws-c-common and aws-checksums.  You will need to build and install them somewhere and then direct cmake to the install directory.

A sample cmake command line that you can adopt to building each package:

```
cmake -DCMAKE_PREFIX_PATH=<install path> -DCMAKE_INSTALL_PREFIX=<install path> <path to project root>
```

Ideally, build instructions should be included in the README, but we haven't gotten to that yet.

**Comment by dmitryash** [comment]
Both `aws-c-common` and `aws-checksums` are built and installed. The problem is that `include()` is not supposed to be used in such way. You need to include `AwsCFlags` into a project, e.g. into folder `cmake` and then set `CMAKE_MODULE_PATH` to local folder so that cmake could find `AwsCFlags`.

AwsCFlags & Co cmake files are installed in a directory which is not known to cmake. I see your project tries to modify `CMAKE_MODULE_PATH` to some system folder:

https://github.com/awslabs/aws-c-event-stream/blob/ceb9f9b85b5887cdae6aa066c500a3650709f448/CMakeLists.txt#L21-L23

This does not work on my system because CMAKE_INSTALL_LIBDIR is absolute path. Yu need to use CMAKE_INSTALL_FULL_LIBDIR:

```cmake
list(APPEND CMAKE_MODULE_PATH "${CMAKE_INSTALL_FULL_LIBDIR}/cmake")
```

As I know `CMAKE_INSTALL_FULL_LIBDIR` will include installation prefix. It should not matter whether CMAKE_INSTALL_LIBDIR is relative path or absolute.

Actually CMAKE_INSTALL_LIBDIR is passed by rpmbuild according to rules specified by OS maintainers.

**Comment by bretambrose** [comment]
If CMAKE_INSTALL_FULL_LIBDIR fixes your issue and results in no behavior changes for other setups, feel free to make a pull request and we'll get it included.

**Comment by FreelandVR** [comment]
I also get a problem here, on Ubuntu for Windows, don't know how to move further. Thankful for any help. I'm trying to run this command and get the same error as the author. cmake -DCMAKE_INSTALL:PREFIX=~/aws_deps -DBUILD_SHARED_LIBS=ON "./"

Best, Alex

**Comment by dmitryash** [comment]
I was need to build rpm package with AWS SDK. I placed cmake files of aws-c-common to cmake modules directory, so cmake could always find them without any modifications to `CMAKE_MODULE_PATH`.

**Comment by dmitryash** [comment]
> I also get a problem here, on Ubuntu for Windows, don't know how to move further. Thankful for any help. I'm trying to run this command and get the same error as the author. cmake -DCMAKE_INSTALL:PREFIX=~/aws_deps -DBUILD_SHARED_LIBS=ON "./"

You probably need to define `-DCMAKE_MODULE_PATH=<path to cmake modules directory>` for cmake command.

**Comment by ColdenCullen** [comment]
> -DCMAKE_INSTALL:PREFIX

This should be `-DCMAKE_INSTALL_PREFIX`, with an underbar, not a colon.

**Comment by FreelandVR** [comment]
Much appreciated guys! I fixed it by setting the install directory of both aws-c-common, aws-checksums to the root of cmake first like you said, and then finally doing the same thing for the event-stream. 

Like this
`cmake -DCMAKE_PREFIX_PATH=/usr/share/cmake -DCMAKE_INSTALL_PREFIX=/usr/share/cmake -DBUILD_SHARED_LIBS=ON "./"` Running this from the corresponding folders, in case anyone has a similar problem.

**Comment by ColdenCullen** [comment]
Glad to hear it worked! Worth noting that you may have different `CMAKE_PREFIX_PATH` and `CMAKE_INSTALL_PREFIX`, assuming:
1. `CMAKE_INSTALL_PREFIX` is where you'd like to install the currently building library (event-stream).
2. `CMAKE_PREFIX_PATH` points to the location where aws-c-common & friends are installed. Also we can make it so that `CMAKE_PREFIX_PATH` may be a list, if you install the dependencies in multiple places. We've done that in all the other libs, so I'll do that here now.

**Comment by ColdenCullen** [comment]
PR merged, you should now be able to install checksums and common to different places if you so choose.

**Comment by LazzariPaolo** [comment]
Hey, I am running into this issue as well.
I am trying to build _aws-c-event-stream_ v0.1.1.

I am using the following flag to run the build:

`CMAKE_PREFIX_PATH="$(AWS_C_COMMON_DIR)/lib/cmake"`

which points to the cmake files in the installed dir on my machine.
In **CMakeLists.txt**, I modified line 22 to the following:

`list(APPEND CMAKE_MODULE_PATH "${CMAKE_INSTALL_PREFIX}/")
`

but I still get the same error. 
Any ideas? Do I need to include _AWS_C_CHECKSUMS_ too? 

Thanks for your help!

**Comment by LazzariPaolo** [comment]
Hi all,

I am working with **aws-c-event-stream v0.1.1**
I was running into the same issue and managed to resolve it by using the following in _CMakeList.txt_:

`list(APPEND CMAKE_MODULE_PATH "${CMAKE_PREFIX_PATH}/")`

This **works when building on Linux and Mac**, but **not on Windows.**

I tried to use:

`list(APPEND CMAKE_MODULE_PATH "${CMAKE_PREFIX_PATH}\")
`

but I am getting the following errors:

```
CMake Error at aws-c-event-stream/CMakeFiles/CMakeTmp/CMakeLists.txt:15:
  Parse error.  Function missing ending ")".  Instead found unterminated
  string with text ")

  target_link_libraries(cmTC_6f34d ${LINK_LIBRARIES})
".

CMake Error at S:/cmake-3.10/Modules/CheckIncludeFile.cmake:56 (try_compile):
Failed to configure test project build system.
```

When I run the make command, I am passing both the location of AWS_COMMON and AWS_CHECKSUMS as CMAKE_PREFIX_PATH. 

Any ideas? Thanks

**Comment by bretambrose** [comment]
Are you setting both CMAKE_PREFIX_PATH and CMAKE_INSTALL_PREFIX?

**Comment by LazzariPaolo** [comment]
Hi @bretambrose

Just the CMAKE_PREFIX_PATH. Do I need the other one too? If so, should it point to the install did of the two libraries? I was under the impression it wasn't needed since it built on Linux and Mac fine.

Thanks for your help, spent all day on this one!

**Comment by bretambrose** [comment]
I am unable to build without setting a value for both.  In my case everything is installing into a single local root directory.  Colden's comment above has more details for the case where the install destination and prefix path are different.

**Comment by LazzariPaolo** [comment]
@bretambrose 

Unfortunately I get the same error with both flags:

- > -D CMAKE_PREFIX_PATH="S:/paolol/win64/aws-c-common/lib/cmake;S:/paolol/win64/aws-c-common/lib/aws-c-common/cmake;S:/paolol/win64/aws-checksums/lib/aws-checksums/cmake"` 


- > -D CMAKE_INSTALL_PREFIX="S:/paolol/win64/aws-c-event-stream/"

where the directory for CMAKE_INSTALL_PREFIX is an empty directory.

Not sure what I am doing wrong. Do the above flags look correct?

**Comment by bretambrose** [comment]
What is your exact cmake command line when you built aws-c-common?

**Comment by LazzariPaolo** [comment]
As follows:

> cmake.exe -D CMAKE_BUILD_TYPE:STRING="Release"  -D CMAKE_INSTALL_PREFIX:PATH=S:/paolol/win64/aws-c-common -D BUILD_SHARED_LIBS:BOOL=ON -D CMAKE_SUPPRESS_REGENERATION:BOOL=ON -G "Visual Studio 15 2017 Win64" -D CMAKE_C_COMPILER:FILEPATH="cl" -D CMAKE_CXX_COMPILER:FILEPATH="cl"

**Comment by bretambrose** [comment]
when you set the prefix path for a depending library like aws-c-event-stream, it should be the install prefix of aws-c-common (and aws-checksums).  You're setting it to a subdirectory of the install location.  Also you can greatly simplify things by installing the libraries to the same root directory, then you don't have to concatentate multiple paths together.

For example, for my development, the same cmake command line builds any library in the entire tree  since I install everything into a single local location:

cmake -DCMAKE_PREFIX_PATH=/home/<snip>/bret/projects/crt/install -DCMAKE_INSTALL_PREFIX=/home/<snip>/bret/projects/crt/install <other options>

**Comment by LazzariPaolo** [comment]
@bretambrose 

Thanks for your help. I decided to upgrade to the latest library version.
I followed your suggestion regarding the prefix path, however I ran into another issue... I opened a separate issue:
https://github.com/awslabs/aws-c-event-stream/issues/27

**Comment by jcnorris00** [comment]
I see that this issue is closed, but I am having the same problem with code that I checked out in the last few days.  I can build aws-c-common and aws-checksums successfully, but I get the cmake errors in the initial post when I thy to configure aws-c-evert-stream.

Aws-c-common and aws-checksums are installed in the same place: ${HOME}/software/aws-sdk .  I have tried the following:

cmake -DCMAKE_PREFIX_PATH=${HOME}/software/aws-sdk -DCMAKE_INSTALL_PREFIX=${HOME}/software/aws-sdk -DCMAKE_MODULE_PATH=${HOME}/software/aws-sdk ~/src/aws-c-event-stream

This is on MacOS 10.13.6 and cmake 3.15.1.

**Comment by ColdenCullen** [comment]
You don't need to explicitly set `CMAKE_MODULE_PATH` from the command line, it's determined by the `CMAKE_PREFIX_PATH`. Try removing that define.
