### ISSUE TITLE
Error implicit declaration of function aws_common_library

### ISSUE THREAD

**Issue by LazzariPaolo** [awslabs/aws-c-event-stream#27]
Hi all,

I am trying to build **aws-c-event-stream v0.1.3**

I have already built **aws-c-common v0.4.3** and **aws-checksums v0.1.3.**

The _CMAKE_PREFIX_PATH_ used in my cmake command is the following:

`CMAKE_PREFIX_PATH="/S:/aws-c-common/;/S:/aws-checksums/`

When building on Linux, I get the following errors:

> /aws-c-event-stream/source/event_stream.c:71:9: error: implicit declaration of function âaws_common_library_initâ [-Werror=implicit-function-declaration]
>          aws_common_library_init(allocator);

> /aws-c-event-stream/source/event_stream.c:79:9: error: implicit declaration of function âaws_unregister_error_infoâ [-Werror=implicit-function-declaration]
>          aws_unregister_error_info(&s_list);
> 
> /aws-c-event-stream/source/event_stream.c:80:9: error: implicit declaration of function âaws_common_library_clean_upâ [-Werror=implicit-function-declaration]
>          aws_common_library_clean_up();
> 
> cc1: all warnings being treated as errors

Do I have to use the latest versions of **aws-c-common** and **aws-checksums** ?

**Comment by bretambrose** [comment]
There isn't a dependency version locking setup for event stream the way there is with the various CRT libraries so if you're building event stream by itself you don't automatically get a compatible c-common.  The init functions were a fairly recent addition so you will probably need to update.

Out of curiosity, why are you building event stream on its own?  I was under the impression that it's only used by the C++ SDK which does peg (and build) compatible versions of common/checksums/event-stream.

**Comment by LazzariPaolo** [comment]
@bretambrose Thanks, that makes sense. I updated aws-c-common too and managed to build on Linux. 

On Windows however, building aws-c-event-stream is still **not working**...

> -- The C compiler identification is MSVC 19.16.27034.0
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stdbool.h
> -- Looking for stdbool.h - found
> -- Performing Test HAS_WGNU
> -- Performing Test HAS_WGNU - Failed
> -- Performing Test HAVE_SYSCONF
> -- Performing Test HAVE_SYSCONF - Failed
> -- Performing Test HAS_SANITIZERS
> -- Performing Test HAS_SANITIZERS - Failed
> -- Looking for pthread.h
> -- Looking for pthread.h - not found
> -- Found Threads: TRUE
> CMake Error at S:/aws-c-common/lib/aws-c-common/cmake/shared/aws-c-common-targets.cmake:81 (message):
>   The imported target "AWS::aws-c-common" references the file
> 
>      "S:/aws-c-common/bin/aws-c-common.dll"
> 
>   but this file does not exist.  Possible reasons include:
> 
>   * The file was deleted, renamed, or moved to another location.
> 
>   * An install or uninstall procedure did not complete successfully.
> 
>   * The installation package was faulty and contained
> 
>      "S:/aws-c-common/lib/aws-c-common/cmake/shared/aws-c-common-targets.cmake"
> 
>   but not all the files it references.
> 
> Call Stack (most recent call first):
>   S:/aws-c-common/lib/aws-c-common/cmake/aws-c-common-config.cmake:5 (include)
>   CMakeLists.txt:86 (find_package)

Why does this error happen? There is no "bin" folder in the "aws-c-common" directory. Why is it expecting it?

**Comment by LazzariPaolo** [comment]
@bretambrose Thanks, I upgraded aws-c-common too to the latest version (as of writing v0.4.11) and got it working now. 
I will be building the whole sdk too, however I need to build these components individually first.
