### ISSUE TITLE
Shall we not call on_prelude() if received prelude is incorrect.

### ISSUE THREAD

**Issue by singku** [awslabs/aws-c-event-stream#28]
https://github.com/awslabs/aws-c-event-stream/blob/0d1e206629e9b4cf7de1ccdb37b7996bb141d05b/source/event_stream.c#L1157-L1159

If service encountered error and respond error as xml document (in several cases like s3 select and transcribe streaming). The prelude resolution logic in above code will try to translate xml document as prelude bytes, result in random values, but `on_prelude` callback in customer application don't know if those prelude data is correct or not. Customer will have to verify the prelude crc by themselves. If they don't do(know) that, there is potential risk of crash. 

My question is shall aws-c-event-stream not call `on_prelude` if crc check failed.

**Comment by JonathanHenson** [comment]
We should probably only fire on_prelude after the check.

**Comment by singku** [comment]
Ok, I created a PR for that.https://github.com/awslabs/aws-c-event-stream/pull/29
