### ISSUE TITLE
Make Aws::S3::S3Client::ComputeEndpointString() public

### ISSUE THREAD

**Issue by dburken** [awslabs/aws-c-event-stream#37]
Could you please change Aws::S3::S3Client::ComputeEndpointString() from private to public? It is useful in troubleshooting endpoints for disconnected systems. 

File: aws-cpp-sdk-s3/include/aws/s3/S3Client.h

Thanks,

**Comment by graebm** [comment]
Wrong repo, I think you meant to post here: https://github.com/awslabs/aws-crt-cpp
