### ISSUE TITLE
  aws-sdk-cpp dependent   aws-c-event-stream  but it Compile error

### ISSUE THREAD

**Issue by lml0001** [awslabs/aws-c-event-stream#42]
[ 75%] Performing download step (git clone) for 'AwsCEventStream'
正克隆到 'AwsCEventStream'...
已经位于 'master'
您的分支与上游分支 'origin/master' 一致。
[ 79%] No patch step for 'AwsCEventStream'
[ 83%] No update step for 'AwsCEventStream'
[ 87%] Performing configure step for 'AwsCEventStream'
-- The C compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:30 (include):
  include could not find load file:

    AwsFindPackage

-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
CMake Error at CMakeLists.txt:77 (aws_use_package):
  Unknown CMake command "aws_use_package".

**Comment by TingDaoK** [comment]
Did you have aws-c-common and aws-c-checksum installed? Please make sure you followed the building instruction for aws-c-event-stream. https://github.com/awslabs/aws-c-event-stream/blob/master/README.md#building

**Comment by TingDaoK** [comment]
Oh, sorry that I didn't see you are compiling aws-sdk-cpp. I guess you may want to open an issue for aws-sdk-cpp instead... aws-c-event-stream should be able to compile as long as the dependency installed correctly.
