### ISSUE TITLE
aws-c-event-stream error during cmake

### ISSUE THREAD

**Issue by rafayhameed** [awslabs/aws-c-event-stream#57]
I have installed aws-c-common and aws-c-checksum. 

Now I am trying to install aws-c-event-stream but getting the error. Steps I am following after installing aws-c-common and aws-c-checksum

1. git clone https://github.com/awslabs/aws-c-event-stream
2. mkdir build && cd build
3. cmake .. -DCMAKE_INSTALL_PREFIX=<deps-install-dir> -DCMAKE_PREFIX_PATH=<deps-install-dir>

I am getting this error after command 3

CMake Error at /home/dev/share/cmake/lib64/cmake/AwsFindPackage.cmake:19 (find_package):
  By not providing "Findaws-c-io.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "aws-c-io",
  but CMake did not find one.

  Could not find a package configuration file provided by "aws-c-io" with any
  of the following names:

    aws-c-ioConfig.cmake
    aws-c-io-config.cmake

  Add the installation prefix of "aws-c-io" to CMAKE_PREFIX_PATH or set
  "aws-c-io_DIR" to a directory containing one of the above files.  If
  "aws-c-io" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:75 (aws_use_package)

-- Configuring incomplete, errors occurred!

**Comment by glaubitz** [comment]
Do you actually have the ```aws-c-io``` package installed?

Also, please be aware that all the AWS C/C++ packages (at least the ones I have touched so far), use non-standard search paths for cmake which is why cmake often fails to find the necessary modules.

See: https://github.com/awslabs/aws-c-event-stream/issues/15

**Comment by JonathanHenson** [comment]
We recently added aws-c-io as a dependency to support event-stream-rpc. You'll need to add that to the modules you check out and build.

**Comment by yhzhou-pds** [comment]
I have installed aws-c-io，and all dependencies install in /usr/local/include/aws/common/ .
I failed during cmake operation。
~/aws-c-event-stream/build/ # cmake -DCMAKE_PREFIX_PATH=/usr/local/include/aws/common -DCMAKE_INSTALL_PREFIX=/usr/local/include/aws/common ../

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found LibCrypto: /usr/local/include/aws/common/lib64/libcrypto.a  
-- LibCrypto Include Dir: /usr/local/include/aws/common/include
-- LibCrypto Shared Lib:  /usr/lib64/libcrypto.so
-- LibCrypto Static Lib:  /usr/local/include/aws/common/lib64/libcrypto.a
CMake Error at /root/aws-c-io/cmake/aws-c-io-config.cmake:13 (include):
  include could not find load file:

    /root/aws-c-io/cmake/static/@PROJECT_NAME@-targets.cmake
Call Stack (most recent call first):
  /usr/local/include/aws/common/lib64/cmake/AwsFindPackage.cmake:19 (find_package)
  CMakeLists.txt:76 (aws_use_package)


-- Configuring incomplete, errors occurred!
See also "/root/aws-c-event-stream/build/CMakeFiles/CMakeOutput.log".
See also "/root/aws-c-event-stream/build/CMakeFiles/CMakeError.log".

**Comment by jmklix** [comment]
Are you still running into this error in the current version?
