### ISSUE TITLE
Are aws_write_* being used properly?

### ISSUE THREAD

**Issue by daniloegea** [awslabs/aws-c-event-stream#8]
They are defined [here](https://github.com/awslabs/aws-c-common/blob/master/include/aws/common/encoding.h) as:
AWS_STATIC_IMPL void aws_write_u64(uint64_t value, uint8_t *buffer)
AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer)
AWS_STATIC_IMPL void aws_write_u24(uint32_t value, uint8_t *buffer)
AWS_STATIC_IMPL void aws_write_u16(uint16_t value, uint8_t *buffer)

But used [here](https://github.com/awslabs/aws-c-event-stream/blob/master/source/event_stream.c) as:

aws_write_u16(buffer_alias, header->header_value_len);
aws_write_u32(message->message_buffer, total_length);
aws_write_u32(buffer_offset, headers_length);
aws_write_u32(buffer_offset, running_crc);
aws_write_u32(buffer_offset, running_crc);
aws_write_u16(header.header_value.static_val, (uint16_t)value);
aws_write_u32(header.header_value.static_val, (uint32_t)value);
aws_write_u64(header.header_value.static_val, (uint64_t)value);
aws_write_u64(header.header_value.static_val, (uint64_t)value);

The build is failing as you can see here https://gist.github.com/daniloegea/3858685358f64104b7bbe4cad6005dd7

Thanks!

**Comment by JonathanHenson** [comment]
https://github.com/awslabs/aws-c-event-stream/pull/10
