### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by zhangfanshcn** [awslabs/aws-c-event-stream#9]
[  9%] Building C object CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o
/home/ubuntu/aws-c-event-stream/source/event_stream.c: In function ‘add_headers_to_buffer’:
/home/ubuntu/aws-c-event-stream/source/event_stream.c:156:31: error: passing argument 1 of ‘aws_write_u16’ makes integer from pointer without a cast [-Werror=int-conversion]
                 aws_write_u16(buffer_alias, header->header_value_len);
                               ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:154:22: note: expected ‘uint16_t {aka short unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u16(uint16_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:156:45: error: passing argument 2 of ‘aws_write_u16’ makes pointer from integer without a cast [-Werror=int-conversion]
                 aws_write_u16(buffer_alias, header->header_value_len);
                                             ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:154:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘uint16_t {aka short unsigned int}’
 AWS_STATIC_IMPL void aws_write_u16(uint16_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c: In function ‘aws_event_stream_message_init’:
/home/ubuntu/aws-c-event-stream/source/event_stream.c:280:23: error: passing argument 1 of ‘aws_write_u32’ makes integer from pointer without a cast [-Werror=int-conversion]
         aws_write_u32(message->message_buffer, total_length);
                       ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint32_t {aka unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:280:48: error: passing argument 2 of ‘aws_write_u32’ makes pointer from integer without a cast [-Werror=int-conversion]
         aws_write_u32(message->message_buffer, total_length);
                                                ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘uint32_t {aka unsigned int}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:282:23: error: passing argument 1 of ‘aws_write_u32’ makes integer from pointer without a cast [-Werror=int-conversion]
         aws_write_u32(buffer_offset, headers_length);
                       ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint32_t {aka unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:282:38: error: passing argument 2 of ‘aws_write_u32’ makes pointer from integer without a cast [-Werror=int-conversion]
         aws_write_u32(buffer_offset, headers_length);
                                      ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘uint32_t {aka unsigned int}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:289:23: error: passing argument 1 of ‘aws_write_u32’ makes integer from pointer without a cast [-Werror=int-conversion]
         aws_write_u32(buffer_offset, running_crc);
                       ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint32_t {aka unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:289:38: error: passing argument 2 of ‘aws_write_u32’ makes pointer from integer without a cast [-Werror=int-conversion]
         aws_write_u32(buffer_offset, running_crc);
                                      ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘uint32_t {aka unsigned int}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:303:23: error: passing argument 1 of ‘aws_write_u32’ makes integer from pointer without a cast [-Werror=int-conversion]
         aws_write_u32(buffer_offset, running_crc);
                       ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint32_t {aka unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:303:38: error: passing argument 2 of ‘aws_write_u32’ makes pointer from integer without a cast [-Werror=int-conversion]
         aws_write_u32(buffer_offset, running_crc);
                                      ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘uint32_t {aka unsigned int}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c: In function ‘aws_event_stream_message_to_debug_str’:
/home/ubuntu/aws-c-event-stream/source/event_stream.c:504:35: error: passing argument 1 of ‘aws_base64_encode’ from incompatible pointer type [-Werror=incompatible-pointer-types]
                 aws_base64_encode(&to_encode, &encode_output);
                                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:69:5: note: expected ‘const struct aws_byte_cursor * restrict’ but argument is of type ‘struct aws_byte_buf *’
 int aws_base64_encode(const struct aws_byte_cursor *AWS_RESTRICT to_encode, struct aws_byte_buf *AWS_RESTRICT output);
     ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:508:35: error: passing argument 1 of ‘aws_base64_encode’ from incompatible pointer type [-Werror=incompatible-pointer-types]
                 aws_base64_encode(&to_encode, &encode_output);
                                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:69:5: note: expected ‘const struct aws_byte_cursor * restrict’ but argument is of type ‘struct aws_byte_buf *’
 int aws_base64_encode(const struct aws_byte_cursor *AWS_RESTRICT to_encode, struct aws_byte_buf *AWS_RESTRICT output);
     ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:539:23: error: passing argument 1 of ‘aws_base64_encode’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     aws_base64_encode(&payload_buffer, &encoded_payload_buffer);
                       ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:69:5: note: expected ‘const struct aws_byte_cursor * restrict’ but argument is of type ‘struct aws_byte_buf *’
 int aws_base64_encode(const struct aws_byte_cursor *AWS_RESTRICT to_encode, struct aws_byte_buf *AWS_RESTRICT output);
     ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c: In function ‘aws_event_stream_add_int16_header’:
/home/ubuntu/aws-c-event-stream/source/event_stream.c:655:19: error: passing argument 1 of ‘aws_write_u16’ makes integer from pointer without a cast [-Werror=int-conversion]
     aws_write_u16(header.header_value.static_val, (uint16_t)value);
                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:154:22: note: expected ‘uint16_t {aka short unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u16(uint16_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:655:51: error: passing argument 2 of ‘aws_write_u16’ makes pointer from integer without a cast [-Werror=int-conversion]
     aws_write_u16(header.header_value.static_val, (uint16_t)value);
                                                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:154:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘short unsigned int’
 AWS_STATIC_IMPL void aws_write_u16(uint16_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c: In function ‘aws_event_stream_add_int32_header’:
/home/ubuntu/aws-c-event-stream/source/event_stream.c:673:19: error: passing argument 1 of ‘aws_write_u32’ makes integer from pointer without a cast [-Werror=int-conversion]
     aws_write_u32(header.header_value.static_val, (uint32_t)value);
                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint32_t {aka unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:673:51: error: passing argument 2 of ‘aws_write_u32’ makes pointer from integer without a cast [-Werror=int-conversion]
     aws_write_u32(header.header_value.static_val, (uint32_t)value);
                                                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:110:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘unsigned int’
 AWS_STATIC_IMPL void aws_write_u32(uint32_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c: In function ‘aws_event_stream_add_int64_header’:
/home/ubuntu/aws-c-event-stream/source/event_stream.c:691:19: error: passing argument 1 of ‘aws_write_u64’ makes integer from pointer without a cast [-Werror=int-conversion]
     aws_write_u64(header.header_value.static_val, (uint64_t)value);
                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:89:22: note: expected ‘uint64_t {aka long unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u64(uint64_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:691:51: error: passing argument 2 of ‘aws_write_u64’ makes pointer from integer without a cast [-Werror=int-conversion]
     aws_write_u64(header.header_value.static_val, (uint64_t)value);
                                                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:89:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘long unsigned int’
 AWS_STATIC_IMPL void aws_write_u64(uint64_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c: In function ‘aws_event_stream_add_timestamp_header’:
/home/ubuntu/aws-c-event-stream/source/event_stream.c:724:19: error: passing argument 1 of ‘aws_write_u64’ makes integer from pointer without a cast [-Werror=int-conversion]
     aws_write_u64(header.header_value.static_val, (uint64_t)value);
                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:89:22: note: expected ‘uint64_t {aka long unsigned int}’ but argument is of type ‘uint8_t * {aka unsigned char *}’
 AWS_STATIC_IMPL void aws_write_u64(uint64_t value, uint8_t *buffer) {
                      ^
/home/ubuntu/aws-c-event-stream/source/event_stream.c:724:51: error: passing argument 2 of ‘aws_write_u64’ makes pointer from integer without a cast [-Werror=int-conversion]
     aws_write_u64(header.header_value.static_val, (uint64_t)value);
                                                   ^
In file included from /home/ubuntu/aws-c-event-stream/source/event_stream.c:20:0:
/home/ubuntu/install/include/aws/common/encoding.h:89:22: note: expected ‘uint8_t * {aka unsigned char *}’ but argument is of type ‘long unsigned int’
 AWS_STATIC_IMPL void aws_write_u64(uint64_t value, uint8_t *buffer) {
                      ^
cc1: all warnings being treated as errors
CMakeFiles/aws-c-event-stream.dir/build.make:62: recipe for target 'CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o' failed
make[2]: *** [CMakeFiles/aws-c-event-stream.dir/source/event_stream.c.o] Error 1
CMakeFiles/Makefile2:355: recipe for target 'CMakeFiles/aws-c-event-stream.dir/all' failed
make[1]: *** [CMakeFiles/aws-c-event-stream.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JonathanHenson** [comment]
sorry for the delay:
https://github.com/awslabs/aws-c-event-stream/pull/10
fixes this issue
